version: '3.1'

services:
  springboot:
    image: ayush199514/spring-boot-mongo:latest
    restart: always
    container_name: springboot
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo  

  mongo:
    image: mongo
    container_name: springboot-mongo
#    ports:
#      - 27018:27017
    volumes:
      - data:/data/db
      - data-bkp:/data/bkp
    restart: always

volumes:
  data:
    external: true
  data-bkp:
    external: true
